name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Gather Network Diagnostics
      run: |
        #!/bin/bash

        # Send GET request to custom server IP and store the response headers and body
        response=$(curl -s -w "%{http_code}" -o /tmp/custom_server_response.html -k https://185.145.255.79)
        
        # Extract the status code from the response
        status_code=$(echo "$response" | tail -n1)
        
        # Calculate the length of the response body
        page_length=$(wc -c < /tmp/custom_server_response.html)
        
        # Print the status code and page length
        echo "HTTP Status Code: $status_code"
        echo "Page Length: $page_length bytes"
        
        # Print response headers for debugging
        curl -I -k https://185.145.255.79

        # Clean up
        rm /tmp/custom_server_response.html
