name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Gather Network Diagnostics
      run: |
        echo "=== Network Configuration ==="
        ip a
        echo "=== DNS Configuration ==="
        cat /etc/resolv.conf
        echo "=== Routing Table ==="
        netstat -rn
        echo "=== Checking DNS resolution for google.com ==="
        nslookup google.com

    - name: Test HTTP connectivity to Google
      run: |
        if curl -s --head https://8.8.8.8 | head -n 1 | grep "HTTP/1.[01] [23].."; then
          echo "Google is reachable via HTTP"
        else
          echo "Google is not reachable via HTTP"
          exit 1
        fi
